stages:
- build
- combine

variables:
  LIBRARIES: |
    libolm/libolm.3.dylib
    libheif/libheif.1.dylib
    aom/libaom.3.dylib
    libvmaf/libvmaf.1.dylib
    jpeg-xl/libjxl.0.6.dylib
    libde265/libde265.0.dylib
    x265/libx265.199.dylib


build amd64:
  tags:
  - macos
  - amd64
  stage: build
  variables:
    MACOSX_DEPLOYMENT_TARGET: "10.13"
  before_script:
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  script:
  - mkdir mautrix-imessage-amd64
  - go build -ldflags "$GO_LDFLAGS" -o mautrix-imessage-amd64/mautrix-imessage
  - |
    for line in $LIBRARIES; do
      IFS='/' read dir dylib <<< "${line}"
      install_name_tool -change /usr/local/opt/$dir/lib/$dylib @rpath/$dylib mautrix-imessage-amd64/mautrix-imessage
      cp /usr/local/opt/$dir/lib/$dylib mautrix-imessage-amd64/
    done
  - install_name_tool -add_rpath @executable_path mautrix-imessage-amd64/mautrix-imessage
  - install_name_tool -add_rpath /usr/local/opt/libolm/lib mautrix-imessage-amd64/mautrix-imessage
  - cp example-config.yaml mautrix-imessage-amd64/
  artifacts:
    paths:
    - mautrix-imessage-amd64
    expire_in: 1 day

build arm64:
  tags:
  - macos
  - arm64
  stage: build
  variables:
    MACOSX_DEPLOYMENT_TARGET: "10.13"
  before_script:
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  - export LIBRARY_PATH=/opt/homebrew/lib
  - export CPATH=/opt/homebrew/include
  - export PATH=/opt/homebrew/bin:$PATH
  script:
  - mkdir mautrix-imessage-arm64
  - go build -ldflags "$GO_LDFLAGS" -o mautrix-imessage-arm64/mautrix-imessage
  - |
    for line in $LIBRARIES; do
      IFS='/' read dir dylib <<< "${line}"
      install_name_tool -change /opt/homebrew/opt/$dir/lib/$dylib @rpath/$dylib mautrix-imessage-arm64/mautrix-imessage
      cp /opt/homebrew/opt/$dir/lib/$dylib mautrix-imessage-arm64/
    done
  - install_name_tool -add_rpath @executable_path mautrix-imessage-arm64/mautrix-imessage
  - install_name_tool -add_rpath /opt/homebrew/opt/libolm/lib mautrix-imessage-arm64/mautrix-imessage
  - install_name_tool -add_rpath /usr/local/opt/libolm/lib mautrix-imessage-arm64/mautrix-imessage
  - cp example-config.yaml mautrix-imessage-arm64/
  artifacts:
    paths:
    - mautrix-imessage-arm64
    expire_in: 1 day

build ios arm64:
  tags:
  - macos
  - arm64
  stage: build
  variables:
    CGO_ENABLED: 1
    GOARCH: arm64
    GOOS: ios
    IPHONEOS_DEPLOYMENT_TARGET: "7.0"
    SDK: iphoneos
    ARCH: arm64
  before_script:
  - export SDK_PATH=$(xcrun -sdk $SDK -show-sdk-path)
  - export CLANG=$(xcrun -sdk $SDK -find clang)
  - export LIBRARY_PATH=$HOME/lib/arm64
  - export CPATH=/opt/homebrew/include
  - export PATH=/opt/homebrew/bin:$PATH
  - export CC=$(pwd)/clangwrap.sh
  - export CXX=$CC
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
  script:
  - mkdir mautrix-imessage-ios-arm64
  - go build -tags ios -ldflags "$GO_LDFLAGS" -o mautrix-imessage-ios-arm64/mautrix-imessage
  - install_name_tool -change build/libolm.dylib.3.2.4 @executable_path/libolm.3.dylib mautrix-imessage-ios-arm64/mautrix-imessage
  - ldid -S mautrix-imessage-ios-arm64/mautrix-imessage
  - cp $HOME/lib/arm64/libolm.dylib mautrix-imessage-ios-arm64/libolm.3.dylib
  - ldid -S mautrix-imessage-ios-arm64/libolm.3.dylib
  artifacts:
    paths:
    - mautrix-imessage-ios-arm64
    expire_in: 1 day

build universal:
  stage: combine
  tags:
  - macos
  - arm64
  variables:
    GIT_STRATEGY: none
  dependencies:
  - build amd64
  - build arm64
  needs:
  - build amd64
  - build arm64
  script:
  - lipo -create -output libolm.3.dylib mautrix-imessage-arm64/libolm.3.dylib mautrix-imessage-amd64/libolm.3.dylib
  - |
    for line in $LIBRARIES; do
      IFS='/' read dir dylib <<< "${line}"
      lipo -create -output $dylib mautrix-imessage-arm64/$dylib mautrix-imessage-amd64/$dylib
    done
  - lipo -create -output mautrix-imessage mautrix-imessage-arm64/mautrix-imessage mautrix-imessage-amd64/mautrix-imessage
  - cp mautrix-imessage-arm64/example-config.yaml .
  artifacts:
    name: mautrix-imessage-universal
    paths:
    - libolm.3.dylib
    - libheif.1.dylib
    - libaom.3.dylib
    - libvmaf.1.dylib
    - libjxl.0.6.dylib
    - libde265.0.dylib
    - libx265.199.dylib
    - mautrix-imessage
    - example-config.yaml
    expire_in: 30 days
